### ISSUE TITLE
createSdkMcpServer() returns object without connect() method, causing query() to fail

### ISSUE THREAD

**Issue by fraser-mendeco** [anthropics/claude-agent-sdk-typescript#12]
## Environment
- **SDK Version:** `@anthropic-ai/claude-agent-sdk@0.1.5`
- **Node.js Version:** `v20.18.1`
- **OS:** Linux

---

## Description

When using `createSdkMcpServer()` to create an SDK MCP server and passing it to `query()` via the `mcpServers` option, the query fails with:

```
TypeError: server.connect is not a function
```

According to the [documentation](https://docs.claude.com/en/api/agent-sdk/typescript#createsdkmcpserver), `createSdkMcpServer()` should return a `McpSdkServerConfigWithInstance` that can be passed directly to `query()`. However, the returned object is missing the `connect()` method that `query()` expects.

---

## Expected Behavior

Based on the documentation and type definitions, SDK MCP servers created with `createSdkMcpServer()` should work seamlessly with `query()`:

```ts
const customServer = createSdkMcpServer({
  name: 'my-tools',
  version: '1.0.0',
  tools: [/* ... */]
});

const result = query({
  prompt: generateMessages(),
  options: {
    mcpServers: {
      'my-tools': customServer  // Should work according to docs
    }
  }
});
```

---

## Actual Behavior

The code throws the following error:

```
TypeError: server.connect is not a function
    at new Query (file:///node_modules/@anthropic-ai/claude-agent-sdk/sdk.mjs:6824:14)
    at createSharedQuery (file:///node_modules/@anthropic-ai/claude-agent-sdk/sdk.mjs:7239:17)
    at query (file:///node_modules/@anthropic-ai/claude-agent-sdk/sdk.mjs:14158:10)
```

---

## Minimal Reproduction

```ts
import { query, tool, createSdkMcpServer } from '@anthropic-ai/claude-agent-sdk';
import { z } from 'zod';

// Create a simple tool
const testTool = tool(
  'test_tool',
  'A test tool',
  { message: z.string() },
  async (args) => ({
    content: [{ type: 'text', text: `Received: ${args.message}` }]
  })
);

// Create SDK MCP server
const testServer = createSdkMcpServer({
  name: 'test-server',
  version: '1.0.0',
  tools: [testTool]
});

// Async generator (required for MCP)
async function* generateMessages() {
  yield {
    type: 'user' as const,
    message: {
      role: 'user' as const,
      content: 'Use the test tool'
    }
  };
}

// This fails with "server.connect is not a function"
const result = query({
  prompt: generateMessages(),
  options: {
    mcpServers: {
      'test-server': testServer
    },
    allowedTools: ['mcp__test-server__test_tool']
  }
});

for await (const message of result) {
  console.log(message);
}
```

---

## Analysis

The issue appears to be that:

1. `query()` spawns a CLI subprocess (observable in stderr logs: *Spawning Claude Code process: node .../cli.js*)
2. The subprocess receives serialized MCP config but needs to call `connect()` on the server instance
3. `createSdkMcpServer()` returns an object **without** the `connect()` method the SDK expects
4. Type definition shows `McpSdkServerConfigWithInstance` should have an instance: `McpServer`, but the returned instance is missing required methods

---

## Workaround

None found for SDK MCP servers.  
Alternative is to use `McpStdioServerConfig` with a standalone MCP server process,  
but this defeats the purpose of in-process SDK servers.

---

## Related Documentation

- [Custom Tools](https://docs.claude.com/en/api/agent-sdk/custom-tools)
- [TypeScript API Reference](https://docs.claude.com/en/api/agent-sdk/typescript#createsdkmcpserver)

**Comment by ashwin-ant** [comment]
I'm able to get your example working on version `0.1.8` of the SDK. Note that I have zod declared in my package.json as `^3.21.4` (we'll be adding this as a peer dependency very soon).

**Comment by canopy-cj** [comment]
Added the same issue https://github.com/anthropics/claude-agent-sdk-typescript/issues/4
